[project]
name = "btc-identity-vault"
description = "Self-sovereign identity on Bitcoin via Stacks"
authors = []
telemetry = false
cache_dir = "./.cache"

[contracts.identity-registry]
path = "contracts/identity-registry.clar"
epoch = "latest"

[contracts.credential-issuer]
path = "contracts/credential-issuer.clar"
epoch = "latest"

[contracts.credential-issuer-v2]
path = "contracts/credential-issuer-v2.clar"
epoch = "latest"

[contracts.credential-issuer-v3]
path = "contracts/credential-issuer-v3.clar"
epoch = "latest"

[contracts.credential-issuer-v4]
path = "contracts/credential-issuer-v4.clar"
epoch = "latest"

[contracts.credential-issuer-v5]
path = "contracts/credential-issuer-v5.clar"
epoch = "latest"

[contracts.credential-issuer-v6]
path = "contracts/credential-issuer-v6.clar"
epoch = "latest"

[contracts.credential-issuer-v7]
path = "contracts/credential-issuer-v7.clar"
epoch = "latest"

[contracts.verification]
path = "contracts/verification.clar"
epoch = "latest"

# Check-checker settings:
# trusted_sender: if true, inputs are trusted after tx_sender has been checked.
# trusted_caller: if true, inputs are trusted after contract-caller has been checked.
# callee_filter: if true, untrusted data may be passed into a private function without a
# warning, if it gets checked inside. This check will also propagate up to the
# caller.
# More informations: https://www.hiro.so/blog/new-safety-checks-in-clarinet

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }
